name: Compiling tests

on:
  push:
    branches:
      - main

jobs:
  install-dependencies:
    name: Install Dependencies
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Teeworlds dependencies
        run: |
          cd resources/
          bash default-dependencies.sh

  build-06version:
    needs: install-dependencies
    name: Build 0.6.x mods
    runs-on: ubuntu-latest
    strategy:
      matrix:
        mod: ['ddnet', 'bomb-tag', 'flagball', 'football', 'hmh-monster', 'hunter', 'infclass', 'killing-floor', 'mmotee', 'streak', 'teesmash', 'teeware', 'zcatch', 'zombpanic']

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Build ${{ matrix.mod }}
        run: |
          cd 0.6.x/${{ matrix.mod }}
          bash compile.sh

  build-07version:
    needs: install-dependencies
    name: Build 0.7.x mods
    runs-on: ubuntu-latest
    strategy:
      matrix:
        mod: ['mmotee', 'nodes']

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Build ${{ matrix.mod }}
        run: |
          cd 0.7.x/${{ matrix.mod }}
          bash compile.sh